// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySpace.Infrastructure.Data;

namespace MySpace.Infrastructure.Data.Migrations.MSSQLServer.MySpaceDb
{
    [DbContext(typeof(MySpaceDbContext))]
    partial class MySpaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MySpace.ApplicationCore.Entities.AppsAggregate.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifyTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<int?>("PasswordId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("PasswordId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("MySpace.ApplicationCore.Entities.AppsAggregate.AppPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ExpiredTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastPasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifyTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("AppPasswords");
                });

            modelBuilder.Entity("MySpace.ApplicationCore.Entities.AppsAggregate.App", b =>
                {
                    b.HasOne("MySpace.ApplicationCore.Entities.AppsAggregate.AppPassword", "Password")
                        .WithMany()
                        .HasForeignKey("PasswordId");
                });
#pragma warning restore 612, 618
        }
    }
}
